title: Aidan Hogden
description: Senior Developer & Army Reservist
baseurl: "" # Leave empty if your site is at username.github.io
url: "https://aidanhogden.dev"

# This helps with the relative_url filters we added
defaults:
  - scope:
      path: ""
    values:
      layout: "post"